### ISSUE TITLE
Plugin is broken (compatibility with markdown package)

### ISSUE THREAD

**Issue by MoritzBrueckner** [rlaboiss/pelican-linkclass#2]
Due to https://github.com/Python-Markdown/markdown/commit/d18c3d0acab0e7469c3284c897afcb61f9dd1fea#diff-797c6da32780122232df19c7a2e709ebL341, the classes `LinkPattern` and `ReferencePattern` are no longer found and building the pelican site fails.

The new classes are now called `LinkInlineProcessor` and `ReferenceInlineProcessor`, and their `handleMatch()` method requires one additional argument.

**Comment by rlaboiss** [comment]
I think I fixed the problem in commit 94dacf488a474c200a358a3e8e16a15e3cf34dfe. Could you please test it?

**Comment by MoritzBrueckner** [comment]
It works like a charm now! Thank you very much :)

Only the pelican plugin repository still needs to be updated, should I file an issue or can you create a PR?

**Comment by rlaboiss** [comment]
I did some extensive testing here, including the update of a production website which uses the linkclass plugin. The unit tests pass also. Everything seems okay and I am hereby closing this issue.

**Comment by rlaboiss** [comment]
Done: https://github.com/getpelican/pelican-plugins/pull/1162
