### ISSUE TITLE
PyPI packaging

### ISSUE THREAD

**Issue by aviskase** [rlaboiss/pelican-linkclass#3]
Hi! What do you think about making this plugin available through PyPI? 

Or, if you don't want to, are you ok with me publishing it?

**Comment by rlaboiss** [comment]
Sorry for the late reply. I have no knowledge of PyPI. Go ahead.

**Comment by rlaboiss** [comment]
I have developed two other Pelican plugins: [pelican_md_graphviz](https://github.com/rlaboiss/pelican_md_graphviz) and [pelican_md_include](https://github.com/rlaboiss/pelican_md_include). Would it also be possible to make them available through PyPI?

**Comment by aviskase** [comment]
I've never published packages on PyPI too, so it would be a first experience for me. What about working together on it? I can prepare pull requests similar to https://github.com/Scheirle/pelican_comment_system/pull/1 and you'll register at PyPi and upload releases.

If it's too much trouble, I'll fork all three repos and do publishing myself.

**Comment by rlaboiss** [comment]
Yes, please, go ahead with the pull requests and I will see how to proceed later.

**Comment by rlaboiss** [comment]
PR #6 has been merged. I am hereby closing this issue report.
