### ISSUE TITLE
Plugin is not importable

### ISSUE THREAD

**Issue by Gullumluvl** [rlaboiss/pelican-linkclass#38]
Hi all,

I am on Ubuntu 22.04 with Python 3.10 and Pip 24.0 and I have installed pelican-linkclass (`python3 -m pip install --user pelican-linkclass`) but it is not importable.

In an interpreter, this causes an ImportError:

    from pelican.plugins import linkclass

whereas it works for the plugin `search` for example.

The distribution info of the plugin is sitting in `~/.local/lib/python3.10/site-packages` with name `pelican_linkclass-2.1.3.dist-info` alongside other namespace plugins such as `search` and `similar-posts` which can be imported normally.
However, contrary to these other plugins, it is not present in the subdirectory `pelican/plugins/`. Accordingly, when running `pelican -D`, we see that it does not discover it in the namespace plugins.

What's causing this? One difference I see is that packaging was done with `pdm` for linkclass, whereas other plugins were packaged with `poetry`.

At the moment I have to clone this repository and manually copy the proper folder into the pelican installation to make it work.

Thanks a lot for your help.

**Comment by justinmayer** [comment]
Thanks for reporting this. I just submitted PR #39, which I believe should address this problem.

Perhaps you could clone that PR's branch, create a new virtual environment, run `pip install build && python -m build && pip install markdown dist/pelican_linkclass-2.1.3.tar.gz`, and see if that addresses the problem in your environment?

**Comment by rlaboiss** [comment]
Thanks for your PR #39, Justin. I merged it and released version 2.1.4 of the plugin. I am hereby closing this issue.

The other plugins that I maintain (avatar, graphviz, and markdown-include) are affected by the same problem. I will fix them ASAP.

**Comment by justinmayer** [comment]
You might want to check whether the `RELEASE.md` file is included in any of the build assets, and if so, add an entry to ensure it is not included.

**Comment by rlaboiss** [comment]
I checked the new sdist tarballs at PyPI for the plugins avatar, graphviz, linkclass, and markdown-include. None of them contains a `RELEASE.md` file.

May I ask why you think that there could be a `RELEASE.md` file in the build assets?

**Comment by Gullumluvl** [comment]
Hi @justinmayer and @rlaboiss ,
sorry for the delayed answer, the updated package is now properly installed :)
Many thanks!

**Comment by justinmayer** [comment]
Because I once saw one in the tarball that appears in the GitHub releases list.

**Comment by rlaboiss** [comment]
> Because I once saw one in the tarball that appears in the GitHub releases list.

Oh, I see. Since the tarballs are generated by autopub, I suppose that this tool is doing its job correctly.

**Comment by rlaboiss** [comment]
> Hi @justinmayer and @rlaboiss , sorry for the delayed answer, the updated package is now properly installed :) Many thanks!

You are welcome. I apologize for any inconvenience that the previous broken version has caused to you.
