### ISSUE TITLE
Convert and release as namespace plugin

### ISSUE THREAD

**Issue by justinmayer** [rlaboiss/pelican-linkclass#9]
This issue tracks the conversion of Link Class to a namespace plugin.

- [x] convert to namespace plugin filesystem layout
- [x] ensure existing test suite passes
- [x] apply community code style standards
- [x] add CI/CD configuration
- [x] release new version to PyPI

**Comment by justinmayer** [comment]
@rlaboiss: I submitted PR #10 to convert Link Class to namespace plugin format. Would you please review and leave any comments over on that pull request? Thanks! 😁

**Comment by rlaboiss** [comment]
Thanks, Justin. I will be overbusy during the next three days. I will take care of this PR as soon as possible and as time permits.

**Comment by rlaboiss** [comment]
I merged PR #10. Thanks a lot for that!

Are there any special things I must pay attention to when releasing a new version to PyPI?

**Comment by rlaboiss** [comment]
> Are there any special things I must pay attention to when releasing a new version to PyPI?

In particular, I see that you replaced `setup.py` by `pyproject.toml`. If you can tell me where I can find the instructions for releasing to PyPI using pyproject & Poetry, I would be grateful.

**Comment by justinmayer** [comment]
Going forward, the intention with all things Pelican is for releases to be automated. If you have a look at the [relevant section of the Contributing documentation](https://docs.getpelican.com/en/latest/contribute.html#using-git-and-github), you will see mention of the `RELEASE.md` file, which is the mechanism via which releases are made and via which packages are published to PyPI. For more background information regarding AutoPub and the benefits of automatic PR-based releases, please see: https://justinmayer.com/projects/autopub/

To that end, I just submitted a pull request containing a `RELEASE.md` file. Since the shift to namespace plugin format could cause confusion for v1 users, I marked the release type as `major`, which will increment the version number from `1.0.0` to `2.0.0` (see [relevant Poetry docs](https://python-poetry.org/docs/cli/#version)). Once any discussion of that PR is concluded, consensus reached, and that PR merged, version 2.0 will be automatically released and published to PyPI via GitHub Actions.

Does that make sense? Anything I can clarify further?

**Comment by rlaboiss** [comment]
This explanation is crystal clear. If that happens really like magic as you describe, then it will be great!

A final question: if I add a Git tag `v2.0.0`, will it interfere with the AutoPub process in any way?

**Comment by justinmayer** [comment]
> if I add a Git tag `v2.0.0`, will it interfere with the AutoPub process in any way?

That would definitely interfere with the automatic publishing process. AutoPub is designed to handle all the steps automatically, including incrementing the version number (via `poetry version`, as noted above) and tagging the release via the `githubrelease` Python package.

That reminds me… AutoPub assumes that version numbers are not v-prefixed (`2.0.0` and not `v2.0.0`). Do you have any strong feelings about that? If not, it would be easier to re-tag from `v1.0.0` to `1.0.0` and continue from there. Otherwise, we would have to figure out how to modify AutoPub to fit v-prefixed version numbers, which isn't going to be very easy.

**Comment by rlaboiss** [comment]
> Do you have any strong feelings about that?

No, it is just because the first tag that I added was `v1.0.0`. I think that this is a general convention on GitHub

> If not, it would be easier to re-tag from `v1.0.0` to `1.0.0` and continue from there. Otherwise, we would have to figure out how to modify AutoPub to fit v-prefixed version numbers, which isn't going to be very easy.

Ok, fair enough. Let us change `v1.0.0` to `1.0.0`.

**Comment by rlaboiss** [comment]
I just merge PR #11. If I understood correctly what you explained, then version 2.0.0 shoud be automatically published on PyPI, shouldn't it? Where will it appear?

**Comment by justinmayer** [comment]
> Ok, fair enough. Let us change `v1.0.0` to `1.0.0`.

Okay, great. ~~I will make that change now.~~ Done!

> If I understood correctly what you explained, then version 2.0.0 shoud be automatically published on PyPI, shouldn't it? Where will it appear?

It should have appeared automatically, just minutes after merging the PR containing the `RELEASE.md` file. (You can monitor the progress via the [Actions](https://github.com/pelican-plugins/linkclass/actions) tab.) In this case, the deployment job was skipped because I overlooked one small detail: the current standard plugin template assumes a primary branch name of `main`, whereas the current primary branch name in this repository is `master`.

We can fix this via one of two methods. We can either [change the primary branch name](https://github.com/github/renaming) to `main` (my preference) or change the deployment configuration from `main` to `master`. I feel like the former would be the more culturally-enlightened choice, but I shall leave the decision up to you. 😊 

What do you think?

**Comment by rlaboiss** [comment]
> We can fix this via one of two methods. We can either [change the primary branch name](https://github.com/github/renaming) to `main` (my preference) or change the deployment configuration from `main` to `master`. I feel like the former would be the more culturally-enlightened choice, but I shall leave the decision up to you. 

Go ahead with `main`. You should add this item to your check list for the next migration.

**Comment by justinmayer** [comment]
> Go ahead with `main`.

Done! To change the branch on your local workstation:

```shell-session
git branch -m master main
git fetch origin
git branch -u origin/main main
```

> You should add this item to your check list for the next migration.

I originally wrote the checklist for migrating plugins from the legacy monolithic plugin repository. I need to create a second, slightly-different checklist for plugins that are coming in from individual repositories. Thank you for this reminder.

The deployment to PyPI was [not successful](https://github.com/pelican-plugins/linkclass/runs/1916109036?check_suite_focus=true#step:5:53), because the `pelicanteam` PyPI account doesn't currently have access to the `pelican-linkclass` PyPI project. This is another item that would have been caught had the aforementioned 2nd checklist existed, so I have ample motivation now to create that.

In the interim, would you please add the `pelicanteam` PyPI account to the `pelican-linkclass` PyPI project via:

[`pelican-linkclass` > Releases](https://pypi.org/manage/project/pelican-linkclass/releases/) > Collaborators > Invite collaborator

**User:** `pelicanteam`
**Role:** Owner

Once that's done, we should be all set to go. Thank you! 😊

**Comment by rlaboiss** [comment]
> The deployment to PyPI was [not successful](https://github.com/pelican-plugins/linkclass/runs/1916109036?check_suite_focus=true#step:5:53), because the `pelicanteam` PyPI account doesn't currently have access to the `pelican-linkclass` PyPI project. 

I was exactly wondering how this could have worked. I was overconfident on the magic capabilities of your AutoPub. :smiley:

**Comment by rlaboiss** [comment]
> In the interim, would you please add the `pelicanteam` PyPI account to the `pelican-linkclass` PyPI project via:
> 
> [`pelican-linkclass` > Releases](https://pypi.org/manage/project/pelican-linkclass/releases/) > Collaborators > Invite collaborator
> 
> **User:** `pelicanteam`
> **Role:** Owner

Done!

**Comment by justinmayer** [comment]
Many thanks, Rafael. Version 2.0 of the Link Class plugin has [been released](https://github.com/pelican-plugins/linkclass/releases/tag/2.0.0) and [published to PyPI](https://pypi.org/project/pelican-linkclass/). 🎉 

Thank you for being so patient. Subsequent releases should go much more smoothly! 😅

**Comment by rlaboiss** [comment]
This is really magic! Thank you very much for your leading work in Pelican and for the setup of all those automated tools. It is much appreciated!

What here now for the migration of my three next plugins…

**Comment by justinmayer** [comment]
> Let us change `v1.0.0` to `1.0.0`.

I almost forgot… You should run the following command in your local clone(s) of this repository in order to ensure the deleted tag is purged (and thus not re-added when you push):

    git pull --prune --tags

**Comment by rlaboiss** [comment]
Ok, thanks.

Could you please remind me the cookbook for doing new releases?
